/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_lsp.h"

bool_t
xdr_Client (XDR *xdrs, Client *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->host, 64))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lsp_client (XDR *xdrs, lsp_client *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->payload, 64))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->length))
		 return FALSE;
	 if (!xdr_Client (xdrs, &objp->client))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_lsp_message (XDR *xdrs, lsp_message *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->connid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->msg_seq_num))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->data, 64))
		 return FALSE;
	return TRUE;
}
