/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCCRACKER_H_RPCGEN
#define _RPCCRACKER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define rpcCracker 0x33319999
#define CAVERLEE4PRES 2

#if defined(__STDC__) || defined(__cplusplus)
#define read 1
extern  char ** read_2(int *, CLIENT *);
extern  char ** read_2_svc(int *, struct svc_req *);
#define write 2
extern  int * write_2(char **, CLIENT *);
extern  int * write_2_svc(char **, struct svc_req *);
extern int rpccracker_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define read 1
extern  char ** read_2();
extern  char ** read_2_svc();
#define write 2
extern  int * write_2();
extern  int * write_2_svc();
extern int rpccracker_2_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCCRACKER_H_RPCGEN */
