/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCCRACKER_H_RPCGEN
#define _RPCCRACKER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define rpcCracker 0x33312345
#define CAVERLEE4PRES 1

#if defined(__STDC__) || defined(__cplusplus)
#define read 1
extern  char ** read_1(void *, CLIENT *);
extern  char ** read_1_svc(void *, struct svc_req *);
#define write 2
extern  int * write_1(char **, CLIENT *);
extern  int * write_1_svc(char **, struct svc_req *);
extern int rpccracker_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define read 1
extern  char ** read_1();
extern  char ** read_1_svc();
#define write 2
extern  int * write_1();
extern  int * write_1_svc();
extern int rpccracker_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCCRACKER_H_RPCGEN */
