/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_lsp.h"

void *
write_2_svc(lsp_client *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

lsp_message *
read_2_svc(void *argp, struct svc_req *rqstp)
{
	static lsp_message  result;

	/*
	 * insert server code here
	 */

	return &result;
}
