/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcCracker.h"

bool_t
xdr_Message (XDR *xdrs, Message *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->connid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->msg_seq_num))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->data, 64))
		 return FALSE;
	return TRUE;
}
