/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct message {
	int size;
	int seq;
	int id;
	long pronum;
	char payload[2048];
};
typedef struct message message;

#define rpcCracker 0x33319999
#define CAVERLEE4PRES 1

#if defined(__STDC__) || defined(__cplusplus)
#define get 1
extern  enum clnt_stat get_1(message *, void *, CLIENT *);
extern  bool_t get_1_svc(message *, void *, struct svc_req *);
extern int rpccracker_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get 1
extern  enum clnt_stat get_1();
extern  bool_t get_1_svc();
extern int rpccracker_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);

#else /* K&R C */
extern bool_t xdr_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
